#!/bin/bash

# ============================================
# Payload CMS Client Project Setup Script
# ============================================
# Automates the setup of a new client project
# Creates isolated PostgreSQL database per project
# ============================================

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  Payload CMS Client Project Setup${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# Clean up any existing Docker containers and volumes from previous runs
echo -e "${BLUE}Cleaning up Docker resources...${NC}"
docker compose down -v 2>/dev/null || true
# Also try to remove any orphaned volumes
if [ -f ../.project-name ]; then
    PROJECT_NAME_TEMP=$(cat ../.project-name | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    VOLUME_NAME="${PROJECT_NAME_TEMP}_postgres_data"
    docker volume rm "$VOLUME_NAME" 2>/dev/null || true
fi
echo -e "${GREEN}✓${NC} Docker cleanup complete"
echo ""

# Detect project name from parent directory or .project-name file
if [ -f ../.project-name ]; then
    PROJECT_NAME=$(cat ../.project-name | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    echo -e "${GREEN}✓${NC} Using project name from .project-name file: ${YELLOW}${PROJECT_NAME}${NC}"
else
    PARENT_DIR=$(basename "$(dirname "$(pwd)")")
    PROJECT_NAME=$(echo "$PARENT_DIR" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

    echo -e "${BLUE}Detected project name: ${YELLOW}${PROJECT_NAME}${NC}"
    echo ""

    # Ask user to confirm or change project name
    read -p "Press Enter to use this name, or type a different name: " USER_INPUT
    if [ ! -z "$USER_INPUT" ]; then
        PROJECT_NAME=$(echo "$USER_INPUT" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
    fi

    echo -e "${GREEN}✓${NC} Using project name: ${YELLOW}${PROJECT_NAME}${NC}"
fi
echo ""

# Create project-specific environment variables
POSTGRES_CONTAINER="${PROJECT_NAME}-postgres"
POSTGRES_DB="${PROJECT_NAME}_db"
POSTGRES_PORT_BASE=5432
POSTGRES_PORT=$POSTGRES_PORT_BASE
CMS_PORT_BASE=3000
CMS_PORT=$CMS_PORT_BASE

# Find available database port if 5432 is taken
echo -e "${BLUE}Checking for available ports...${NC}"
while lsof -Pi :$POSTGRES_PORT -sTCP:LISTEN -t >/dev/null 2>&1 || nc -z localhost $POSTGRES_PORT >/dev/null 2>&1 ; do
    POSTGRES_PORT=$((POSTGRES_PORT + 1))
done

if [ $POSTGRES_PORT -ne $POSTGRES_PORT_BASE ]; then
    echo -e "${YELLOW}⚠${NC}  Database port 5432 is in use, using port ${POSTGRES_PORT} instead"
else
    echo -e "${GREEN}✓${NC}  Database port: ${YELLOW}${POSTGRES_PORT}${NC}"
fi

# Find available CMS port if 3000 is taken
while lsof -Pi :$CMS_PORT -sTCP:LISTEN -t >/dev/null 2>&1 || nc -z localhost $CMS_PORT >/dev/null 2>&1 ; do
    CMS_PORT=$((CMS_PORT + 1))
done

if [ $CMS_PORT -ne $CMS_PORT_BASE ]; then
    echo -e "${YELLOW}⚠${NC}  CMS port 3000 is in use, using port ${CMS_PORT} instead"
else
    echo -e "${GREEN}✓${NC}  CMS port: ${YELLOW}${CMS_PORT}${NC}"
fi
echo ""

# Step 1: Install dependencies
echo ""
echo -e "${BLUE}Step 1: Installing dependencies...${NC}"
if pnpm install; then
    echo -e "${GREEN}✓${NC} Dependencies installed"
else
    echo -e "${RED}✗${NC} Failed to install dependencies"
    exit 1
fi

# Step 2: Generate secrets
echo ""
echo -e "${BLUE}Step 2: Generating secure secrets...${NC}"
PAYLOAD_SECRET=$(openssl rand -hex 32)
REVALIDATION_SECRET=$(openssl rand -hex 32)
PREVIEW_SECRET=$(openssl rand -hex 32)
echo -e "${GREEN}✓${NC} Secrets generated"

# Step 3: Create .env file
echo ""
echo -e "${BLUE}Step 3: Creating .env file...${NC}"
cat > apps/cms/.env << ENDOFENV
# ===========================================
# Payload CMS Environment Variables
# ===========================================
# Auto-generated by setup.sh
# Project: ${PROJECT_NAME}
# Generated: $(date)

# -------------------------------------------
# Database Configuration (REQUIRED)
# -------------------------------------------
# PostgreSQL connection string
# Project-specific database: ${POSTGRES_DB}
DATABASE_URL=postgresql://payload:payload_secret@localhost:${POSTGRES_PORT}/${POSTGRES_DB}

# -------------------------------------------
# Payload CMS Configuration (REQUIRED)
# -------------------------------------------
# Secret key for JWT signing and encryption
PAYLOAD_SECRET=${PAYLOAD_SECRET}

# Public URL of the CMS server
PAYLOAD_PUBLIC_SERVER_URL=http://localhost:${CMS_PORT}

# -------------------------------------------
# Frontend Configuration (REQUIRED)
# -------------------------------------------
# Public URL of the frontend site
NEXT_PUBLIC_SITE_URL=http://localhost:${CMS_PORT}

# Internal CMS URL for server-side requests
CMS_URL=http://localhost:${CMS_PORT}

# Secret for on-demand revalidation (ISR)
REVALIDATION_SECRET=${REVALIDATION_SECRET}

# -------------------------------------------
# Live Preview Configuration
# -------------------------------------------
# Secret for secure preview token generation
PREVIEW_SECRET=${PREVIEW_SECRET}

# -------------------------------------------
# Node Environment
# -------------------------------------------
NODE_ENV=development

# -------------------------------------------
# Docker Configuration (for this project)
# -------------------------------------------
POSTGRES_USER=payload
POSTGRES_PASSWORD=payload_secret
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
COMPOSE_PROJECT_NAME=${PROJECT_NAME}

# -------------------------------------------
# CMS Server Port
# -------------------------------------------
# Auto-assigned to avoid conflicts with other running projects
CMS_PORT=${CMS_PORT}

# -------------------------------------------
# Email Configuration (Optional)
# -------------------------------------------
# Uncomment and configure for email functionality
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_SECURE=false
# SMTP_USER=your-smtp-username
# SMTP_PASS=your-smtp-password
# EMAIL_FROM_NAME=Payload CMS
# EMAIL_FROM_ADDRESS=noreply@example.com
ENDOFENV

echo -e "${GREEN}✓${NC} .env file created at apps/cms/.env"
echo -e "${BLUE}   Database: ${YELLOW}${POSTGRES_DB}${NC}"

# Also create .env in root for docker-compose
cat > .env << ENDOFENV
POSTGRES_USER=payload
POSTGRES_PASSWORD=payload_secret
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_PORT=${POSTGRES_PORT}
CMS_PORT=${CMS_PORT}
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
ENDOFENV

echo -e "${GREEN}✓${NC} .env file created at .env for docker-compose"
echo -e "${BLUE}   Port: ${YELLOW}${POSTGRES_PORT}${NC}"
echo -e "${BLUE}   Container: ${YELLOW}${POSTGRES_CONTAINER}${NC}"

# Step 4: Start PostgreSQL with project-specific settings
echo ""
echo -e "${BLUE}Step 4: Starting PostgreSQL database...${NC}"
echo -e "${BLUE}   Using project-specific container and volume${NC}"

# Export environment variables for docker-compose
export COMPOSE_PROJECT_NAME=${PROJECT_NAME}
export POSTGRES_DB=${POSTGRES_DB}
export POSTGRES_PORT=${POSTGRES_PORT}

if docker compose up -d postgres; then
    echo -e "${GREEN}✓${NC} PostgreSQL started"
    echo -e "${BLUE}   Container: ${YELLOW}${PROJECT_NAME}-postgres-1${NC}"
    echo -e "${BLUE}   Volume: ${YELLOW}${PROJECT_NAME}_postgres_data${NC}"
else
    echo -e "${RED}✗${NC} Failed to start PostgreSQL"
    exit 1
fi

# Wait for PostgreSQL to be ready
echo -e "${BLUE}Waiting for PostgreSQL to be ready...${NC}"
sleep 5

# Step 5: Run migrations
echo ""
echo -e "${BLUE}Step 5: Running database migrations...${NC}"
if make db-migrate; then
    echo -e "${GREEN}✓${NC} Database migrations completed"
else
    echo -e "${RED}✗${NC} Failed to run migrations"
    exit 1
fi

# Step 6: Verify package.json scripts use environment variables
echo ""
echo -e "${BLUE}Step 6: Verifying dev scripts for dynamic ports...${NC}"

# Check if CMS package.json already uses PORT variable
if [ -f "apps/cms/package.json" ]; then
    if grep -q 'PORT=\${CMS_PORT' apps/cms/package.json; then
        echo -e "${GREEN}✓${NC} apps/cms/package.json already configured for dynamic ports"
    else
        echo -e "${YELLOW}⚠${NC}  apps/cms/package.json needs manual update to use PORT=\${CMS_PORT:-3000}"
        echo -e "${YELLOW}   This should be fixed in the repository${NC}"
    fi
fi

# Check if Astro package.json exists and uses PORT variable
if [ -f "apps/astro/package.json" ]; then
    if grep -q 'ASTRO_PORT' apps/astro/package.json; then
        echo -e "${GREEN}✓${NC} apps/astro/package.json already configured for dynamic ports"
    else
        echo -e "${YELLOW}⚠${NC}  apps/astro/package.json may need update for dynamic ports"
    fi
fi

# Success!
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  ✓ Setup Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "${BLUE}Project Configuration:${NC}"
echo -e "  Name: ${YELLOW}${PROJECT_NAME}${NC}"
echo -e "  Database: ${YELLOW}${POSTGRES_DB}${NC}"
echo -e "  Database Port: ${YELLOW}${POSTGRES_PORT}${NC}"
echo -e "  CMS Port: ${YELLOW}${CMS_PORT}${NC}"
echo -e "  Container: ${YELLOW}${PROJECT_NAME}-postgres-1${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo -e "  1. Start the development server:"
echo -e "     ${YELLOW}make dev${NC}"
echo ""
echo -e "  2. Open your browser:"
echo -e "     ${YELLOW}http://localhost:${CMS_PORT}/admin${NC}"
echo ""
echo -e "  3. Create your first admin user"
echo ""
echo -e "${BLUE}Your secrets (saved in apps/cms/.env):${NC}"
echo -e "  PAYLOAD_SECRET: ${YELLOW}${PAYLOAD_SECRET}${NC}"
echo ""
echo -e "${YELLOW}Note: This project has its own isolated database.${NC}"
echo -e "${YELLOW}You can run multiple client projects simultaneously!${NC}"
echo -e "${YELLOW}Dev scripts automatically configured to use dynamic ports.${NC}"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
echo ""

